# Generated by Django 4.0.5 on 2022-07-06 06:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_rename_cleint_request_client_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client_Request',
            new_name='ClientRequest',
        ),
    ]
