# Generated by Django 4.0.5 on 2022-07-07 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_rename_client_request_clientrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
