# Generated by Django 4.0.5 on 2022-07-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_clientrequest_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='username',
            field=models.CharField(default='', max_length=150, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
