# Generated by Django 4.0.5 on 2022-07-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_clientrequest_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
    ]
