# Generated by Django 4.0.5 on 2022-07-13 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_clientrequest_options_changerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='client_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_request', to='accounts.clientrequest', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='error',
            field=models.TextField(default='', verbose_name='Message'),
        ),
    ]
