# Generated by Django 4.0.5 on 2022-07-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_changerequest_client_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='success',
            field=models.BooleanField(default=False, verbose_name='Pushed'),
        ),
    ]
