# Generated by Django 4.0.5 on 2022-07-05 08:23

from django.db import migrations, models
import modifier_admin.password


class Migration(migrations.Migration):

    dependencies = [
        ('modifier_admin', '0002_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(default=modifier_admin.password.random_password, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
