# Generated by Django 4.0.5 on 2022-07-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modifier_admin', '0005_profile_auto_generated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
